services:
  postgres:
    image: postgres:15
    container_name: smartplanner-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  smartplanner:
    image: smartplanner
    build:
      context: .
      dockerfile: SmartPlanner/Dockerfile
    container_name: smartplanner-backend
    ports:
      - "5058:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=${DB_CONNECTION}
      - ASPNETCORE_URLS=http://+:80
      - Jwt__Key=${JWT_KEY}
    networks:
      - app-network

  frontend:
    image: smartplanner-frontend
    build:
      context: ./frontendplanner
      dockerfile: Dockerfile
    container_name: smartplanner-frontend
    ports:
      - "5173:80"
    depends_on:
      - smartplanner
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge